### ISSUE TITLE
Build Failure: Post-Merge Compilation Error

### ISSUE THREAD

**Issue by HeartlessVeteran2** [Heartless-Veteran/komikku-2026#50]
Build is still failing after merging PR #48.

## Failed Runs
- Build Debug: #22688079086
- PR Build: #22688078549
- Delete Merged Branch: #22688078650

### 1. ReadingStatsRepository Parameters
The  call may have incorrect parameters. Current call:

Need to verify this matches the actual function signature.

### 2. Missing @Inject Annotation
 class may need  constructor annotation for dependency injection.

### 3. Additional Import Issues
There may be other unresolved references not caught in the initial fix.

## Action Items
- [ ] Check build logs on GitHub Actions for exact error
- [ ] Verify GetHistory.subscribe() parameter types
- [ ] Add @Inject annotation if needed
- [ ] Check for other compilation errors

**Priority:** High - Blocks all builds
